name: E2E tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto' # Use Temurin distribution of OpenJDK
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.8 # Замените на нужную версию Gradle
          wrapper-cache-enabled: true

      - name: Create .env file
        run: |
          echo "SERVER_PORT=8084" > .env
          echo "SENDER_EMAIL_ADDRESS=${{ secrets.SENDER_EMAIL_ADDRESS }}" >> .env
          echo "SENDER_EMAIL_PASSWORD=${{ secrets.SENDER_EMAIL_PASSWORD }}" >> .env
          echo "SMTP_SERVER=${{ secrets.SMTP_SERVER }}" >> .env
          echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> .env
          echo "RECIPIENT_EMAIL_ADDRESS=${{ secrets.RECIPIENT_EMAIL_ADDRESS }}" >> .env

      - name: Build and Run app in Docker
        run: |
          docker compose up -d --build
          docker ps

      - name: Wait for app to be ready
        run: |
          until curl -s http://localhost:8084; do
            echo "Waiting for app to start..."
            sleep 5
          done

      - name: Run tests
        run: ./gradlew test --tests "LoginFeatureTest"

